### ISSUE TITLE
upgrade to latest openseadragon?

### ISSUE THREAD

**Issue by jrochkind** [cbeer/openseadragon-rails#27]
Current master [appears to package](https://github.com/cbeer/openseadragon-rails/blob/e1a93060e2598bf7475ea53a94c144a9b6e2f564/vendor/assets/javascripts/openseadragon/openseadragon.js) openseadragon 2.3.0

As I write this, current latest openseadragon seems to be [2.4.1](https://github.com/openseadragon/openseadragon/tree/v2.4.1)

Would you welcome a PR to update the embedded openseadragon? (And then do a release with it?)

If so, can you give any guidance on how to prepare this? Is there any automation for packaging up latest openseadragon in this gem, or any tips for manually doing it?  

Even if not the latter, if you can give me some encouragement that if I prepare a PR you will have time to review/merge and do a release, then I will try to find time to do so!

**Comment by mejackreed** [comment]
Resolved in #28

**Comment by jrochkind** [comment]
Thanks!

For anyone else coming along...  I actually switched to using openseadragon via webpacker, no longer via this gem.  Worked out fine for me, and is perhaps preferable if you are already using webpacker. 

1. Add openseadragon to package.json, eg 
2. in a webpacker controlled file, just do `import OpenSeadragon from 'openseadragon';` You could put it in your `application.js`, or in a file imported into application.js, etc. 

If you want the default openseadragon CSS or images, you might need to do more things to get them via webpacker, but I don't think I did for my uses.
